language: java
sudo: false # faster builds

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11

os:
  - linux
  - osx
  - windows

before_install:
  - pip install --user codecov

after_success:
  - codecov
